# Generated by Django 4.2.2 on 2023-09-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationlog',
            name='language_used',
            field=models.CharField(choices=[('hi', 'Hindi'), ('gu', 'Gujarati'), ('th', 'Telegu'), ('ta', 'Tamil'), ('es', 'Spanish'), ('mr', 'Marathi')], max_length=200),
        ),
    ]
